[terminal]
shell = "nu"

[font]
normal = { family = "DejaVu Sans Mono" }
size = 20

[[hints.enabled]]
command         = "xdg-open" # On Linux/BSD
# command       = "open" # On macOS
# command       = { program = "cmd", args = [ "/c", "start", "" ] } # On Windows
hyperlinks      = true
post_processing = true
persist         = false
mouse.enabled   = true
mouse.mods = "Control"
binding         = { key = "O", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘\\\\]+"
